#!/bin/bash
# Copyright 2018 Donour Sizemore
#
# This file is part of RacePi
#
# RacePi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# RacePi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RacePi.  If not, see <http://www.gnu.org/licenses/>.

set -eo pipefail

ARCH=$(uname -m)

MINICONDA_LOCATION="http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-${ARCH}.sh"
LOCAL_FILE="$HOME/miniconda.sh"

if [ ! -e "$LOCAL_FILE" ]; then
    wget "$MINICONDA_LOCATION" -O "$LOCAL_FILE"
fi

chmod +x "$LOCAL_FILE"
"$LOCAL_FILE" -b -f

source ~/miniconda3/bin/activate root
conda update conda -y
conda update pip -y
conda install sqlalchemy -y
#conda install anaconda-client -y
#conda install bokeh -y
pip install --upgrade pip
pip install gps3 pybluez
pip install cantools
source deactivate

echo "== RacePi Conda Environment Configuration Success =="
