#!/bin/bash
# Copyright 2016 Donour Sizemore
#
# This file is part of RacePi
#
# RacePi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# RacePi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RacePi.  If not, see <http://www.gnu.org/licenses/>.

# Create empty db file with proper schema

# Schema for the database. The order is important because
# tables use foreign keys.
SCHEMA_FILES=(           \
    "schema/session.sql" \
    "schema/gps.sql"     \
    "schema/imu.sql"     \
    "schema/can.sql"     \
)

if [ -z $1 ]; then
    echo "Usage: $0 <filename>" >&2
    exit 1
fi
OUTPUT_FILE=$1

echo "Looking up sqlite3"
SQLITE=$(which sqlite3)
if [ -z ${SQLITE} ]; then
    echo "Failed to find SQLITE"
    exit 1
fi
echo "[SQLITE3]: using $SQLITE" 

TMPFILE=$(mktemp)

# setup automatic cleanup of tmpfile
function cleanup {
    rm "${TMPFILE}"
}
trap cleanup EXIT

echo "[Created tmpfile]: ${TMPFILE}" 

set -eu -o pipefail

${SQLITE} ${TMPFILE} ".databases"
for f in "${SCHEMA_FILES[@]}"
do
    echo "Importing ${f}"
    cat "${f}" | ${SQLITE} ${TMPFILE}
done

cp -i $TMPFILE ${OUTPUT_FILE}

echo "[Success] ${OUTPUT_FILE}"
